name: trendy_closet
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  bloc: ^9.0.0
  bloc_test: ^10.0.0
  blur: ^4.0.0
  dio: ^5.7.0
  retrofit: ^4.4.1
  injectable: ^2.5.0
  intl: any
  json_annotation: ^4.9.0
  get_it: ^8.0.2
  pretty_dio_logger: ^1.4.0
  flutter_svg: ^2.0.14
  flutter_bloc: ^9.0.0
  device_preview: ^1.2.0
  http:
  share_plus:
  auto_size_text: ^3.0.0
  flutter_launcher_icons: ^0.14.3
  device_info_plus: ^11.3.0
  permission_handler: ^11.3.1
  path_provider:
  google_fonts: ^6.1.0
  get: ^4.6.5
  carousel_slider: ^5.0.0
  cached_network_image: ^3.3.1



flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/Logo.png"
  #flutter pub run flutter_launcher_icons -f Logo.png
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  injectable_generator: ^2.6.2
  json_serializable: ^6.8.0
  lints: ^5.0.0
  retrofit_generator: ^9.1.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/images/
    - assets/fonts/
